# Generated by Django 5.2 on 2025-05-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_imageupload_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='userquary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('queary_sub', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=200)),
            ],
        ),
    ]
