# Generated by Django 5.2 on 2025-05-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='staff_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
