# Generated by Django 5.2 on 2025-05-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_customuser_staff_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='s_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
