# Generated by Django 5.2 on 2025-05-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_customuser_s_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='department',
            new_name='s_name',
        ),
    ]
