# Generated by Django 5.2 on 2025-05-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_department_customuser_s_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='staff_email',
            new_name='staf_email',
        ),
    ]
