# Generated by Django 5.2 on 2025-05-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_staff_email_customuser_staf_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='staf_email',
            new_name='s_email',
        ),
    ]
