# Generated by Django 5.2 on 2025-05-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_staf_email_customuser_s_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='clg_reg',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='clg_roll',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
