# Generated by Django 5.2 on 2025-05-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_customuser_clg_reg_alter_customuser_clg_roll_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='s_email',
        ),
    ]
