# Generated by Django 5.2 on 2025-06-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_customuser_s_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='acc_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semster', models.CharField(max_length=4)),
                ('degree', models.CharField(max_length=40)),
                ('course_type', models.CharField(max_length=20)),
                ('course_dur', models.CharField(max_length=10)),
            ],
        ),
    ]
