# Generated by Django 5.2 on 2025-06-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_acc_details_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='clg_roll',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
